name             'wpt'
maintainer       'Jeff Blaisdell'
maintainer_email '?'
license          'Apache v2'
description      'Installs/Configures wpt'
long_description 'Installs/Configures wpt'
version          '0.1.0'

depends 'apt', '~> 2.5.2'
depends 'apache2', '~> 2.0.0'
depends 'php', '~> 1.4.6'
